name:                due-date-calculator
version:             1.0.0.0
github:              "zellermario/due-date-calculator"
author:              "Zeller Mario"
maintainer:          "zellermario@me.com"

description:         Please see the README on GitHub at <https://github.com/zellermario/due-date-calculator#readme>

dependencies:
- base >= 4.7 && < 5
- time

library:
  source-dirs: src
  dependencies:
    - time

tests:
  due-date-calculator-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - due-date-calculator
    - QuickCheck